name: cti-stix-commom-objects daily update
on:
  push
  # schedule:
    # * is a special character in YAML so you have to quote this string
  #  - cron:  '?'

jobs:
  build:

    runs-on: ubuntu-latest

    name: Update Stix Commom Objects Repository
    steps:
    - name: Checkout STIX Common Objects Repo
      uses: actions/checkout@v2
    - name: Checkout CVE Repo
      uses: actions/checkout@v2
      with:
        repository: CVEProject/cvelist
        path: './cvelist'
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install and update essential dependencies
      run: |
        pip install -U pip setuptools wheel
        pip install pycountry requests stix2 stix2-validator
    - name: Run Updater
      run: |
        python scripts/generate_common_objects.py -r mapping.csv ./cvelist objects
    - name: Validate STIX Content
      run: |
        python scripts/validate_content.py -v "--version 2.1" objects
        rm -rf cvelist/
    - name: Commit changes back
      if: ${{ success() }}
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git status
        git commit -m "generated latest"
        git push
